version: '3'

services:
  db:
    image: mariadb
    container_name: wordpress-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d



  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    deploy:
      replicas: 3

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl/selfsigned.pem:/usr/local/etc/haproxy/ssl/selfsigned.pem:ro
    depends_on:
      - wordpress
  

volumes:
  db_data:
